name: Run backup

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: mysqldump --host=${{ secrets.ACTIONKIT_DB_HOST }} --user='${{ secrets.ACTIONKIT_DB_USER }}' --password='${{ secrets.ACTIONKIT_DB_PASSWORD }}' --skip-lock-tables --no-tablespaces --routines --triggers --compress --compact --databases '${{ secrets.ACTIONKIT_DB_NAME }}' | gzip | aws s3 cp - s3://'${{ secrets.AWS_S3_BUCKET_NAME }}'/'${{ secrets.ACTIONKIT_DB_NAME }}'.sql.gz
